---
version: "3.9"
services:
  nop:
    build:
      context: .
    networks:
      - nop
    ports:
      - target: 5000
        published: 30000
        protocol: tcp
        mode: host
# this is for nop commerce file
  nop-db:
    image: mysql:8
    networks:
      - nop
    volumes:
      - nop-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_USER=nop
      - MYSQL_PASSWORD=rootroot
      - MYSQL_DATABASE=nop
volumes:
  nop-db:
networks:
  nop:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.103.0/24